global_pruning:
  layers:
  - conv1
  - conv2
  - fc1
  - fc2
  - fc3
  sparsity: 0.2
local_pruning:
  Conv2d:
  - weight
  - 0.07
  Linear:
  - weight
  - 0.07
method: RandomUnstructured
model: VGG16
